
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 05 20:30:47 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {

  // region EOF
  public static int EOF = 0;
  // endregion

  // region Types
  public static int INT = 1;
  public static int BOOL = 2;
  public static int CHAR = 3;
  // endregion

  // region Null
  public static int NULL = 4;
  // endregion

  // region Operators

  // region Arithmetic
  public static int ADD = 5;
  public static int SUBTRACT = 6;
  public static int MULTIPLY = 7;
  public static int DIVIDE = 8;
  public static int MODULO = 9;
  // endregion

  // region Relational
  public static int EQUAL = 10;
  public static int NOT_EQUAL = 11;
  public static int GREATER = 12;
  public static int GREATER_EQUAL = 13;
  public static int LESS = 14;
  public static int LESS_EQUAL = 15;
  // endregion

  // region Logical
  public static int AND = 16;
  public static int OR = 17;
  // endregion

  // region Assignment
  public static int ASSIGN = 18;
  // endregion

  // region Increment and decrement
  public static int INCREMENT = 19;
  public static int DECREMENT = 20;
  // endregion

  // region Separators
  public static int SEPARATOR = 21;
  public static int COMMA = 22;
  public static int POINT = 23;
  // endregion

  // region Encolsures
  public static int LEFT_PARENTHESIS = 24;
  public static int RIGHT_PARENTHESIS = 25;
  public static int LEFT_BRACKET = 26;
  public static int RIGHT_BRACKET = 27;
  public static int LEFT_BRACE = 28;
  public static int RIGHT_BRACE = 29;
  // endregion

  // endregion

  // region Keywords
  public static int PROGRAM = 30;
  public static int CLASS = 31;
  public static int EXTENDS = 32;
  public static int IF = 33;
  public static int ELSE = 34;
  public static int NEW = 35;
  public static int DO = 36;
  public static int WHILE = 37;
  public static int RETURN = 38;
  public static int BREAK = 39;
  public static int CONTINUE = 40;
  public static int PRINT = 41;
  public static int READ = 42;
  public static int VOID = 43;
  public static int CONST = 44;
  // endregion

  // region Constants
  public static int INT_VALUE = 45;
  public static int CHAR_VALUE = 46;
  public static int BOOL_VALUE = 47;
  // endregion

  // region Identifier
  public static int IDENTIFIER = 48;
  // endregion

  // region Error
  public static int ERROR = 49;
  // endregion

}

